### ISSUE TITLE
LLVM_EXPERIMENTAL_TARGETS_TO_BUILD

### ISSUE THREAD

**Issue by linyoufa** [matter-labs/compiler-llvm#6]
-- Building with -fPIC
CMake Error at CMakeLists.txt:848 (message):
  The target `EraVM' is experimental and must be passed via
  LLVM_EXPERIMENTAL_TARGETS_TO_BUILD.

**Comment by hedgar2017** [comment]
@linyoufa please update your `zkevm-llvm` tool with `cargo install compiler-llvm-builder`.
